--- #YAML:1.0
name:                Tell
version:             0.0.5
abstract:            Print messages with balance, indentation, severity, and autoclosure.
license:             ~
author:              
    - Steve Roscio <roscio@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scope::Upper:                  0.06
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
